version: "3.8"

services:
  words:
    build: .
    image: random_words_image
    container_name: random_words_container
    ports:
      - "5050:5000"
    volumes:
      - ./docker_logs/:/random_words/logs/
    command: flask run -h 0.0.0.0 -p 5000